FROM node:10
MAINTAINER Facundo Gonzalez <facugon@theeye.io>

ENV destDir /src/theeye/agent
RUN mkdir -p ${destDir}
WORKDIR ${destDir}
COPY . ${destDir}

RUN apt update && apt install -y build-essential \
      && npm install -g pkg \
      && cd ${destDir} \
      && ls -l . \
      && bash ./misc/compiler.sh \
      && bash ./misc/packager.sh

CMD ["bin/theeye-agent"]
