FROM node:10
MAINTAINER Facundo Gonzalez <facugon@theeye.io>

ENV destDir /src/theeye/agent
RUN mkdir -p ${destDir}
WORKDIR ${destDir}
COPY . ${destDir}

# Locales and base tools
RUN apt-get update && apt-get install -y jq imagemagick locales build-essential \
      && sed -i 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen \ 
      && locale-gen en_US.UTF-8

# set system-wide locale settings
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8
ENV LC_ALL en_US.UTF-8
# verify modified configuration
RUN dpkg-reconfigure --frontend noninteractive locales  

RUN npm install -g pkg \
      && cd ${destDir} \
      && ls -l . \
      && bash ./misc/compiler.sh \
      && bash ./misc/packager.sh

CMD ["bin/theeye-agent"]
