FROM node:16
MAINTAINER Facundo Gonzalez <facugon@theeye.io>

ARG DEBIAN_FRONTEND=noninteractive
ENV destDir /src/theeye/agent
RUN mkdir -p ${destDir}
WORKDIR ${destDir}
COPY . ${destDir}

# Locales and base tools
RUN apt update -qqq \
      && apt install -y --no-install-recommends gcc g++ make jq curl imagemagick locales build-essential ripmime poppler-utils isync rename tzdata mpack mutt git gnupg wget \
      && sed -i 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen \ 
      && locale-gen en_US.UTF-8

# set system-wide locale settings
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8
ENV LC_ALL en_US.UTF-8

# verify modified configuration
RUN dpkg-reconfigure --frontend noninteractive locales  

RUN npm install -g pkg \
      && cd ${destDir} \
      && ls -l . \
      && bash ./misc/compiler.sh "linux" "node16"\
      && bash ./misc/packager.sh

CMD ["bin/theeye-agent"]
